set(0, 'DefaultFigureColor', 'White','DefaultFigurePaperType','a4letter', 'DefaultAxesColor', 'white', 'DefaultAxesDrawmode', 'fast', 'DefaultAxesFontUnits', 'points', 'DefaultAxesFontSize', 15, 'DefaultAxesFontAngle', 'normal',... 
'DefaultAxesFontName', 'Times', ...
'DefaultAxesFontWeight', 'bold', ...
'DefaultAxesGridLineStyle', ':', ...
'DefaultAxesInterruptible', 'on', ...
'DefaultAxesLayer', 'Bottom', ...
'DefaultAxesNextPlot', 'replace', ...
'DefaultAxesUnits', 'normalized', ...
'DefaultAxesXcolor', [0, 0, 0], ...
'DefaultAxesYcolor', [0, 0, 0], ...
'DefaultAxesZcolor', [0, 0, 0], ...
'DefaultAxesVisible', 'on', ...
'DefaultLineLineStyle', '-', ...
'DefaultLineLineWidth', 1, ...
'DefaultLineMarkerSize', 30, ...
'DefaultTextColor', [0, 0, 0], ...
'DefaultTextFontUnits', 'Points', ...
'DefaultTextFontSize', 10,... 
'DefaultLegendFontSize',10,...
'DefaultTextFontName', 'Times',... 
'DefaultTextVerticalAlignment', 'middle',... 
'DefaultTextHorizontalAlignment', 'left');